//
// Created by ceduardo on 18/05/2021.
//

#ifndef DATABASE_PREPARERESULT_H
#define DATABASE_PREPARERESULT_H

typedef enum { PREPARE_SUCCESS, PREPARE_UNRECOGNIZED_STATEMENT, PREPARE_SYNTAX_ERROR } PrepareResult;

#endif //DATABASE_PREPARERESULT_H
